language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require codeclimate/php-test-reporter --dev
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi


script:
- phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
- CODECLIMATE_REPO_TOKEN="37434aae18b66ed935dd46c3de4c9b2538e02ab97f8f8f44ac6a80b695e9297d" vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"
